<?php

declare(strict_types=1);

/**
 * @var MageMonk\GoogleSignOn\Block\AuthenticationPopup $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php $scriptString = 'window.googleSignOn = ' . /* @noEscape */ $block->getSerializedConfig(); ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<script>
    window.googleSignOn = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
</script>
